require "condeco/version"
require "condeco/authenticator"
require 'condeco/bookings'
require 'condeco/location'
require 'condeco/region'
require 'condeco/rooms'
require 'condeco/client'
require 'condeco/values/country'
require 'condeco/values/credential'
