require 'rest-client'
require 'active_support/core_ext/object'
require "condeco/version"
require "condeco/authenticator"
require 'condeco/bookings'
require 'condeco/location'
require 'condeco/region'
require 'condeco/rooms'
require 'condeco/countries'
require 'condeco/users'
require 'condeco/client'
require 'condeco/values/country'
require 'condeco/values/credential'
